name = "openai-api-mock"
type = "javascript"  # Specify the type of Worker

main = "src/index.js"  # Entry point for the Worker
compatibility_date = "2024-04-04"  # Date used for feature compatibility

[build]
command = "npm install"  # Optional: Build command if needed

[workers_dev]
compatibility_date = "2024-04-04"  # Compatibility date for local development

[ai]
binding = "AI"  # Binding for AI module

[account]
id = "61947e5008a3d17e8d3f7909fb2beba9"  # Replace with your Cloudflare account ID

[env.production]
workers_dev = false  # Set to true if deploying to Workers Dev environment
compatibility_date = "2024-04-04"  # Ensure the compatibility date matches
